#pragma once

enum class DIRECTION {
	LEFT = 0, TOP, RIGHT, BOTTOM,
	LEFT_TOP, LEFT_BOTTOM, RIGHT_TOP, RIGHT_BOTTOM,
	DIRECTION_NUM
};

enum IMAGE_LOAD_KIND {
	LOAD_RESOURCE = 0,
	LOAD_FILE,
	LOAD_EMPTY,
	LOAD_END
};

enum class MONOBEHAVIOUR_TYPE {
	MONOBEHAVIOUR, BLOCK, BULLET, BUTTON,
	DAMAGE, MUZZLE_FLASH, EFFECT,
	ENEMY, BOSS, PLAYER,
	PLAYER_SKILL,
	TYPE_NUM
};